# Generated by Django 2.0.5 on 2018-11-12 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plp_edmodule', '0013_auto_20170919_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalmodulerating',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='educationalmodulerating',
            name='user',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(help_text='png, размер файла не более 1 мб, разрешение не более 1000*1000', upload_to='benefit_icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='benefitlink',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'plp_edmodule'), ('model', 'educationalmodule')), models.Q(('app_label', 'plp'), ('model', 'course')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип объекта, к которому выгода'),
        ),
        migrations.AlterField(
            model_name='coursepromotion',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'plp_edmodule'), ('model', 'educationalmodule')), models.Q(('app_label', 'plp'), ('model', 'course')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='cover',
            field=models.ImageField(blank=True, help_text='Минимум 345*220, картинки большего размера будут сжаты до этого размера', upload_to='edmodule_cover', verbose_name='Обложка EM'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='status',
            field=models.CharField(choices=[('hidden', 'Скрыт'), ('direct', 'Доступ по ссылке'), ('published', 'Опубликован')], default='hidden', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='от 1 до 3 элементов, каждый с новой строки', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='educationalmodule',
            name='vacancies',
            field=models.TextField(blank=True, default='', help_text='HTML блок', verbose_name='Вакансии'),
        ),
        migrations.AlterField(
            model_name='educationalmoduleenrollmentreason',
            name='payment_type',
            field=models.CharField(choices=[(None, ''), ('manual', 'manual'), ('yamoney', 'yamoney'), ('other', 'other')], default=None, max_length=16, null=True, verbose_name='Способ платежа'),
        ),
        migrations.AlterField(
            model_name='educationalmoduleenrollmenttype',
            name='mode',
            field=models.CharField(blank=True, choices=[('audit', 'audit'), ('honor', 'honor'), ('verified', 'verified')], help_text='course mode в edx', max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='product_type',
            field=models.CharField(choices=[('course', 'Курс'), ('edmodule', 'Специализация')], default='course', max_length=10, verbose_name='Тип продукта'),
        ),
        migrations.DeleteModel(
            name='EducationalModuleRating',
        ),
    ]
