# Generated by Django 2.0.5 on 2019-01-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plp', '0003_auto_20181022_2004'),
        ('plp_edmodule', '0014_auto_20181112_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdmoduleCourse',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('plp.course',),
        ),
    ]
